/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ComposableStablePool } from "./ComposableStablePool";
export * as factories from "./factories";
export { ComposableStablePool__factory } from "./factories/ComposableStablePool__factory";
